### PR TITLE
Added support for datatype(range) in supported properties

### LINKED ISSUE #88: Implement copying of data types properties
### I'm submitting a 
- [x ] feature request.

If the declaration of a type for a field is present in the original ontology, it should be copied in the ApiDoc to allow `hydrus` to read it and genreate the right column type.

Necessary for https://github.com/HTTP-APIs/hydrus/issues/581

### PR DESCRIPTION
**Pull request by farazkhanfk7**
Fixes #88 

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.5.2 and above.

### Description

Database columns should be created with datatype as String, Integer or Float according to types defined in the ApiDoc or Ontology via properties like `"range":  "xsd:decimal"` as discussed. For this implementation changes have to be made in both doc_writer and doc_maker.
```
{
      "@type": "SupportedProperty",
      "property": "URL..../NonPerformingLoan.jsonld#LegalEntityIdentifier",
      "range": "https://www.w3.org/TR/xmlschema-2/#integer",
      "readable": "true",
      "required": "true",
      "title": "LegalEntityIdentifier",
      "writeable": "true"
}
```
### Change logs
- Added `xsd` to Context
- Changes in HydraClassProp in doc_writer
- Changes in create_property function in doc_maker
- Updated sample docs with w3.org `@context` in HydraStatus

### CODE REVIEW

**Comment by farazkhanfk7** [comment]
Also, currently I am using `rdfs:range` from namespace. Because we have defined `range` in context as:
```
"range": {
   "@id": "rdfs:range",
   "@type": "@id"
}
```
I can change it to `"range": "hydra:range"`  but we're already using `rdfs['range']` or `rdfs['domain']` throughout doc_maker. So, we'll have to change it to `hydra['range']` as well. If allowed I can make that change too.

**Comment by Mec-iS** [comment]
please @chrizandr @sameshl @priyanshunayan confirm that the usage of `rdf:range` is not necessary because we have `hydra:range` that is effectively a alias for it.
Can we double-check where it is used and if can remove this doubled declaration so Hasan can proceed?

**Comment by Mec-iS** [comment]
@farazkhanfk7 to not make things stuck here, could you provide support for all possible keys with `range`, `rdfs:range`, and `hydra:range` just by checking with a `in` condition: `if "range" in supportedprop.keys()` or similar?

**Comment by farazkhanfk7** [comment]
Yes sounds good. Thanks, I'll make the change.

**Review by Mec-iS — APPROVED** [review]

**Pull request merged**
