### PR TITLE
Created a new package for hydraspec

### PR DESCRIPTION
**Pull request by shravandoda**
Kindly use the following command to install -- 
`pip install -e git+https://github.com/ShravanDoda/hydra-python-core@develop#egg=hydraspec`.
Consider using virtual environment else you'll need superuser privileges.

### CODE REVIEW

**Comment by shravandoda** [comment]
Once this is done, I'll make changes to the hydrus codebase so that hydraspec can be fetched from the requirements.txt file. Also we can create OpenAPI parser into its own package.

**Review by Mec-iS — CHANGES_REQUESTED** [review]
History of commits has to be preserved. You cannot just copy/paste the code as all the history of the codebase before is erased. Please use proper git commands.

**Comment by shravandoda** [comment]
Which branch's history should be preserved? Master or Develop?

**Comment by Mec-iS** [comment]
branching always happens on master

**Comment by de-sh** [comment]
@Mec-iS  Have we got to also name the module as hydraspec?

**Pull request closed without merging**
