### PR TITLE
hydra core fetching in context changed to hydraCG core.jsonld

### LINKED ISSUE #74: Change hydra core fetching in context.
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

hydra core is being fetched from https://www.markus-lanthaler.com/hydra/core

### Expected Behaviour:

It should be fetched from the hydraCG core.jsonld

### Do you want to work on this issue?

yes

### PR DESCRIPTION
**Pull request by Purvanshsingh**
Fixes #74 

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.5.2 and above.

### Description

The hydra core fetching in context is changed to http://www.hydra-cg.com/spec/latest/core/core.jsonld

### CODE REVIEW

**Comment by Mec-iS** [comment]
Probably the most reliable source is https://raw.githubusercontent.com/HydraCG/Specifications/master/spec/latest/core/core.jsonld

**Comment by Purvanshsingh** [comment]
> Probably the most reliable source is https://raw.githubusercontent.com/HydraCG/Specifications/master/spec/latest/core/core.jsonld

I think this will be more stable as well.
Thanks for the review.
I have updated the source.

**Review by chrizandr — APPROVED** [review]

**Comment by Mec-iS** [comment]
@sameshl the target branch is wrong. The current main is `develop`.

**Comment by sameshl** [comment]
@Mec-iS Oh, I missed that. Should I revert my merge commit?

**Comment by Mec-iS** [comment]
@sameshl please align `develop` with `master` and then merge the lastest changes to `develop`

**Comment by Mec-iS** [comment]
Fixed. Main branch is `develop`

**Pull request merged**
