### PR TITLE
Edit setup.py, README and import statements 

### PR DESCRIPTION
**Pull request by shravandoda**
@Mec-iS kindly review.

### CODE REVIEW

**Comment by Mec-iS** [comment]
why did you remove the `samples` directory?

it may be useful for developers to read examples for the ApiDoc

**Comment by de-sh** [comment]
> it may be useful for developers to read examples for the ApiDoc
Yes, I think the same @ShravanDoda

**Comment by shravandoda** [comment]
@Mec-iS

**Comment by Mec-iS** [comment]
@shravanDoda you cannot just add back the files, please use `git reset` to move back in the commit log or re-branch and re-apply the changes

**Comment by shravandoda** [comment]
@Mec-iS please refer to #5

**Pull request closed without merging**
