### PR TITLE
Sync to master

### PR DESCRIPTION
**Pull request by Mec-iS**

### CODE REVIEW

**Review by xadahiya — APPROVED** [review]
Looks good!

**Review by gustavodemorais — COMMENTED** [review]
Hey @vddesai1871 is the **hydra_doc_sample.py** here working with hydrus? We have the drone API under this name in hydrus and the Agent, here we have the Pet Store one, which I wasn't able to make it work previously.

Wanted to have the Drone API in this repo so we maintain it aligned with the spec as the main doc since we're using it a lot in the Agent and hydrus.

**Comment by vddesai1871** [comment]
>Hey @vddesai1871 is the hydra_doc_sample.py here working with hydrus? 

I hadn't run it in a while but on getting your comment I tried it and it is working fine for me except for one extra forward slash`/` it had in entry point URIs. I have corrected it. If you are facing any other error, I can look into that too.

>Wanted to have the Drone API in this repo so we maintain it aligned with the spec as the main doc since we're using it a lot in the Agent and hydrus.

Yeah, it makes sense. It would be better to use drone vocab at all places from `hydra-flock-vocab` repos as suggested here https://github.com/HTTP-APIs/hydra-flock-vocab/issues/1 but first it would require us to update vocab at hydra-flock-vocab, so I have opened a PR there. 
I am using urllib to get the raw jsonld file from my `hydra-flock-vocab` fork and use it, not sure whether that's the right way to do it...

**Review by vddesai1871 — APPROVED** [review]

**Comment by xadahiya** [comment]
Merging #29

**Comment by gustavodemorais** [comment]
Yeah, I agree it's better to have it in hydra-flock-vocab. Thanks for the correction in the Pet example, I'll continue the discussion at https://github.com/HTTP-APIs/hydra-flock-vocab/issues/1.

**Pull request merged**
